---
galaxy_info:
  author: arpatek
  description: Installs Oh My Zsh with the gg3 custom theme, aliases, and zshrc
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions: all
    - name: Ubuntu
      versions: all
dependencies:
  - role: core_utils
