---
galaxy_info:
  author: arpatek
  description: Timezone, locale and MOTD
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: EL
      versions: ["all"]
    - name: Debian
      versions: ["all"]
    - name: Ubuntu
      versions: ["all"]
dependencies: []
